### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lCyou** [lCyou/did-web-server#4]
- [ ] not deleted did document when jwt who has did docment isnt verified
- [ ] how straged indexddb? most important
- [ ] vc display (qr-code?)
- [ ] display dids which user have
